# Website Setup
title:               Antonio Aguirre
tagline:             "Bayesian Statistics·Machine Learning"
description:         "Statistics and more."
url:                 "https://antonio-aguirre.com" # Website URL
baseurl:             ""                           # Leave empty for root deployment
paginate:            5                             # Number of posts per page
permalink:           pretty                        # Clean, user-friendly URLs

# Logo Configuration
logo:                "/files/images/logo.png"      # Path to the logo file

# Teaching Information
course_names:
  stat131: "STAT131: Probability Theory"
  stat132: "STAT132: Classical and Bayesian Inference"

# Author Information
author:
  name:              Antonio Aguirre
  url:               https://github.com/AntonioAPDL
  email:             jaguir26@ucsc.edu

# Social media
social_media:
  github: https://github.com/AntonioAPDL
  linkedin: https://www.linkedin.com/in/AntonioAPDL
  twitter: https://twitter.com/AntonioAPDL
  bsky: antonioaguirre.bsky.social
  email: mailto:jaguir26@ucsc.edu

# Plugins
plugins:
  - jekyll-paginate  # Enable pagination for blog posts

# Custom Variables
version:             1.1.0
google_analytics_id: ""  # Add Google Analytics ID if applicable

# Example configuration for custom CSS
markdown: kramdown
theme: minima
highlighter: rouge

# Add this if you haven't already
sass:
  style: compressed

# Ensure custom CSS is referenced correctly
include:
  - public/css/

