# Basic Site Settings
locale: "en-US"
title: "Antonio Aguirre"
title_separator: "-"
name: &name "Antonio Aguirre"
description: &description "PhD Candidate in Statistics at UC Santa Cruz, specializing in Bayesian modeling and time series analysis."
url: https://antonio-aguirre.com
baseurl: "" # The subpath of your site, e.g., "/blog"
repository: "AntonioAPDL/antonio-aguirre.github.io"

# Site Author - Sidebar Info
author:
  avatar: "profile.png"
  name: "Antonio Aguirre"
  pronouns: # e.g., "he/him"
  bio: "Statistics PhD student with a passion for research, teaching, and exploring data-driven insights."
  location: "Santa Cruz, CA"
  employer: "UC Santa Cruz"
  uri: "https://antonio-aguirre.com"
  email: 
    - "jaguir26@ucsc.edu"
    - "antonio.agprz@gmail.com"
  
  # Academic websites
  googlescholar: # Avoided as requested
  arxiv: # Add if relevant
  researchgate: # Add if relevant
  
  # Repositories and social media
  github: "AntonioAPDL"
  twitter: "AntonioAPDL"
  bluesky: "https://antonioaguirre.bsky.social"
  linkedin: "https://linkedin.com/in/AntonioAPDL"

# Theme and Appearance
theme: "minimal-mistakes"
palette:
  primary: "#445D48" # Olive green
  secondary: "#FDE5D4" # Rosy creme
  accent: "#D6CC99" # Almost mint
  dark: "#001524" # Almost black
  highlight: "#5E3023" # Espresso
logo: # Keep empty for now; you can add a personal logo later

# Language Settings
lang: "en"
multilingual:
  enabled: true
  available_languages:
    - "English"
    - "Spanish"
    - "German"

# Blog Settings
blog:
  title: "Blog"
  description: "Posts on statistics, philosophy, politics, and more."

# Teaching Section
teaching:
  enabled: true
  title: "Teaching"
  description: "Resources and materials for courses taught by Antonio Aguirre."
  sections:
    - "Fall 2024: Probability Theory"
    - "Teaching Philosophy"
    - "Workshops and Fellowships"
    - "Project Resources"
  drive_links: true # Enable for Google Drive embedding

# Deployment
domain: "antonio-aguirre.com"

# Analytics
analytics:
  provider: false # Can be updated with Google Analytics tracking ID later

# Conversion and Plugins
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives and Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Appearance and Layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Social Sharing and SEO
social:
  type: "Person"
  links:
    - "https://github.com/AntonioAPDL"
    - "https://twitter.com/AntonioAPDL"
    - "https://antonioaguirre.bsky.social"
    - "https://linkedin.com/in/AntonioAPDL"
