# Setup
title:               Antonio Aguirre
tagline:             'Bayesian Statistics and Machine Learning'
description:         'A professional site showcasing research and projects in Bayesian statistics, spatio-temporal modeling, and machine learning.'
url:                 "https://antonio-aguirre.com"  # Your actual website URL
baseurl:             ""  # Leave empty if the site is deployed at the root
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Antonio Aguirre
  url:               https://github.com/AntonioAPDL
  email:             jaguir26@ucsc.edu

# Social media
social_media:
  github:            https://github.com/AntonioAPDL
  linkedin:          https://www.linkedin.com/in/AntonioAPDL
  twitter:           https://twitter.com/AntonioAPDL
  email:             mailto:jaguir26@ucsc.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y  # Add your Google Analytics ID if applicable
