[build]
  command = "bundle exec jekyll build"
  ignore = "./scripts/netlify-ignore-build.sh"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.3.4"
  BUNDLER_VERSION = "2.5.23"
