#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 <artifact-path> [artifact-path ...]" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIVE_DATA_BRANCH="${LIVE_DATA_BRANCH:-live-data}"
REMOTE="${LIVE_DATA_REMOTE:-origin}"
COMMIT_MESSAGE="${LIVE_DATA_COMMIT_MESSAGE:-chore: update live data artifacts}"
RUN_ID="${GITHUB_RUN_ID:-manual}"
LIVE_PARENT="$(mktemp -d "${RUNNER_TEMP:-/tmp}/live-data-worktree-${RUN_ID}.XXXXXX")"
LIVE_DIR="${LIVE_PARENT}/repo"
LOCAL_BRANCH="live-data-publish-${RUN_ID}-$$"

cleanup() {
  git -C "${REPO_ROOT}" worktree remove --force "${LIVE_DIR}" >/dev/null 2>&1 || true
  git -C "${REPO_ROOT}" branch -D "${LOCAL_BRANCH}" >/dev/null 2>&1 || true
  rm -rf "${LIVE_PARENT}"
}
trap cleanup EXIT

cd "${REPO_ROOT}"

artifacts=()
for artifact in "$@"; do
  if [[ "${artifact}" = /* || "${artifact}" == *".."* ]]; then
    echo "Refusing unsafe artifact path: ${artifact}" >&2
    exit 2
  fi
  if [[ ! -f "${artifact}" ]]; then
    echo "Artifact not found: ${artifact}" >&2
    exit 2
  fi
  artifacts+=("${artifact}")
done

branch_exists=0
if git ls-remote --exit-code --heads "${REMOTE}" "${LIVE_DATA_BRANCH}" >/dev/null 2>&1; then
  branch_exists=1
  git fetch "${REMOTE}" "${LIVE_DATA_BRANCH}:refs/remotes/${REMOTE}/${LIVE_DATA_BRANCH}"
  git worktree add -B "${LOCAL_BRANCH}" "${LIVE_DIR}" "${REMOTE}/${LIVE_DATA_BRANCH}"
else
  git worktree add --detach "${LIVE_DIR}" HEAD
  git -C "${LIVE_DIR}" switch --orphan "${LOCAL_BRANCH}"
  git -C "${LIVE_DIR}" rm -r --ignore-unmatch . >/dev/null 2>&1 || true
fi

validate_artifact_for_publish() {
  local artifact="$1"
  LIVE_DATA_LOCAL_PATH="${REPO_ROOT}/${artifact}" \
  LIVE_DATA_EXISTING_PATH="${LIVE_DIR}/${artifact}" \
  LIVE_DATA_ALLOW_OLDER="${LIVE_DATA_ALLOW_OLDER:-0}" \
  LIVE_DATA_MAX_AGE_HOURS="${LIVE_DATA_MAX_AGE_HOURS:-}" \
  python3 - <<'PY'
import datetime as dt
import json
import os
import sys
from pathlib import Path


def parse_time(value):
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        parsed = dt.datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def artifact_time(path):
    if path.suffix.lower() != ".json" or not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    candidates = [
        data.get("generated_at_utc"),
        data.get("generated_utc"),
        data.get("init_time_utc"),
    ]
    init_times = data.get("init_times")
    if isinstance(init_times, dict):
        candidates.extend(init_times.values())
    parsed = [parse_time(value) for value in candidates]
    parsed = [value for value in parsed if value is not None]
    return max(parsed) if parsed else None


local_path = Path(os.environ["LIVE_DATA_LOCAL_PATH"])
existing_path = Path(os.environ["LIVE_DATA_EXISTING_PATH"])
allow_older = os.environ.get("LIVE_DATA_ALLOW_OLDER") == "1"
max_age_raw = os.environ.get("LIVE_DATA_MAX_AGE_HOURS", "").strip()

current_ts = artifact_time(local_path)
existing_ts = artifact_time(existing_path)

if current_ts and existing_ts and current_ts < existing_ts and not allow_older:
    print(
        f"Refusing to publish older artifact {local_path}: "
        f"candidate={current_ts.isoformat()} existing={existing_ts.isoformat()}",
        file=sys.stderr,
    )
    raise SystemExit(8)

if max_age_raw:
    try:
        max_age_hours = float(max_age_raw)
    except ValueError:
        print(f"Invalid LIVE_DATA_MAX_AGE_HOURS={max_age_raw!r}", file=sys.stderr)
        raise SystemExit(2)
    if current_ts is None:
        print(f"Cannot enforce freshness for {local_path}: no parseable artifact timestamp.", file=sys.stderr)
        raise SystemExit(9)
    age_hours = (dt.datetime.now(dt.timezone.utc) - current_ts).total_seconds() / 3600.0
    if age_hours > max_age_hours:
        print(
            f"Refusing to publish stale artifact {local_path}: "
            f"age={age_hours:.1f}h max={max_age_hours:.1f}h",
            file=sys.stderr,
        )
        raise SystemExit(9)
PY
}

for artifact in "${artifacts[@]}"; do
  validate_artifact_for_publish "${artifact}"
  mkdir -p "${LIVE_DIR}/$(dirname "${artifact}")"
  cp "${REPO_ROOT}/${artifact}" "${LIVE_DIR}/${artifact}"
done

if [[ ! -f "${LIVE_DIR}/README.md" ]]; then
  cat > "${LIVE_DIR}/README.md" <<'EOF'
# Live Data Artifacts

This branch stores public JSON/CSV artifacts generated by scheduled GitHub Actions.
The website reads selected forecast files from this branch so routine data refreshes
do not trigger Netlify production deploys.
EOF
fi

if ! git -C "${LIVE_DIR}" config user.name >/dev/null; then
  git -C "${LIVE_DIR}" config user.name "github-actions[bot]"
fi
if ! git -C "${LIVE_DIR}" config user.email >/dev/null; then
  git -C "${LIVE_DIR}" config user.email "github-actions[bot]@users.noreply.github.com"
fi

git -C "${LIVE_DIR}" add README.md "${artifacts[@]}"

if git -C "${LIVE_DIR}" diff --cached --quiet; then
  echo "No live-data artifact changes to publish."
  exit 0
fi

git -C "${LIVE_DIR}" commit -m "${COMMIT_MESSAGE}"

for attempt in 1 2 3; do
  if git -C "${LIVE_DIR}" push "${REMOTE}" "HEAD:${LIVE_DATA_BRANCH}"; then
    echo "Published live data artifacts to ${LIVE_DATA_BRANCH}."
    exit 0
  fi

  if [[ "${attempt}" -eq 3 ]]; then
    break
  fi

  echo "Push rejected; rebasing on latest ${LIVE_DATA_BRANCH} and retrying (${attempt}/3)." >&2
  git -C "${LIVE_DIR}" fetch "${REMOTE}" "${LIVE_DATA_BRANCH}:refs/remotes/${REMOTE}/${LIVE_DATA_BRANCH}"
  if ! git -C "${LIVE_DIR}" rebase "${REMOTE}/${LIVE_DATA_BRANCH}"; then
    git -C "${LIVE_DIR}" rebase --abort || true
    echo "Could not rebase live data changes cleanly." >&2
    exit 1
  fi
done

echo "Failed to publish live data artifacts after retries." >&2
exit 1
