#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 <artifact-path> [artifact-path ...]" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIVE_DATA_BRANCH="${LIVE_DATA_BRANCH:-live-data}"
REMOTE="${LIVE_DATA_REMOTE:-origin}"
COMMIT_MESSAGE="${LIVE_DATA_COMMIT_MESSAGE:-chore: update live data artifacts}"
RUN_ID="${GITHUB_RUN_ID:-manual}"
LIVE_PARENT="$(mktemp -d "${RUNNER_TEMP:-/tmp}/live-data-worktree-${RUN_ID}.XXXXXX")"
LIVE_DIR="${LIVE_PARENT}/repo"
LOCAL_BRANCH="live-data-publish-${RUN_ID}-$$"

cleanup() {
  git -C "${REPO_ROOT}" worktree remove --force "${LIVE_DIR}" >/dev/null 2>&1 || true
  git -C "${REPO_ROOT}" branch -D "${LOCAL_BRANCH}" >/dev/null 2>&1 || true
  rm -rf "${LIVE_PARENT}"
}
trap cleanup EXIT

cd "${REPO_ROOT}"

artifacts=()
for artifact in "$@"; do
  if [[ "${artifact}" = /* || "${artifact}" == *".."* ]]; then
    echo "Refusing unsafe artifact path: ${artifact}" >&2
    exit 2
  fi
  if [[ ! -f "${artifact}" ]]; then
    echo "Artifact not found: ${artifact}" >&2
    exit 2
  fi
  artifacts+=("${artifact}")
done

branch_exists=0
if git ls-remote --exit-code --heads "${REMOTE}" "${LIVE_DATA_BRANCH}" >/dev/null 2>&1; then
  branch_exists=1
  git fetch "${REMOTE}" "${LIVE_DATA_BRANCH}:refs/remotes/${REMOTE}/${LIVE_DATA_BRANCH}"
  git worktree add -B "${LOCAL_BRANCH}" "${LIVE_DIR}" "${REMOTE}/${LIVE_DATA_BRANCH}"
else
  git worktree add --detach "${LIVE_DIR}" HEAD
  git -C "${LIVE_DIR}" switch --orphan "${LOCAL_BRANCH}"
  git -C "${LIVE_DIR}" rm -r --ignore-unmatch . >/dev/null 2>&1 || true
fi

for artifact in "${artifacts[@]}"; do
  mkdir -p "${LIVE_DIR}/$(dirname "${artifact}")"
  cp "${REPO_ROOT}/${artifact}" "${LIVE_DIR}/${artifact}"
done

if [[ ! -f "${LIVE_DIR}/README.md" ]]; then
  cat > "${LIVE_DIR}/README.md" <<'EOF'
# Live Data Artifacts

This branch stores public JSON/CSV artifacts generated by scheduled GitHub Actions.
The website reads selected forecast files from this branch so routine data refreshes
do not trigger Netlify production deploys.
EOF
fi

if ! git -C "${LIVE_DIR}" config user.name >/dev/null; then
  git -C "${LIVE_DIR}" config user.name "github-actions[bot]"
fi
if ! git -C "${LIVE_DIR}" config user.email >/dev/null; then
  git -C "${LIVE_DIR}" config user.email "github-actions[bot]@users.noreply.github.com"
fi

git -C "${LIVE_DIR}" add README.md "${artifacts[@]}"

if git -C "${LIVE_DIR}" diff --cached --quiet; then
  echo "No live-data artifact changes to publish."
  exit 0
fi

git -C "${LIVE_DIR}" commit -m "${COMMIT_MESSAGE}"

for attempt in 1 2 3; do
  if git -C "${LIVE_DIR}" push "${REMOTE}" "HEAD:${LIVE_DATA_BRANCH}"; then
    echo "Published live data artifacts to ${LIVE_DATA_BRANCH}."
    exit 0
  fi

  if [[ "${attempt}" -eq 3 ]]; then
    break
  fi

  echo "Push rejected; rebasing on latest ${LIVE_DATA_BRANCH} and retrying (${attempt}/3)." >&2
  git -C "${LIVE_DIR}" fetch "${REMOTE}" "${LIVE_DATA_BRANCH}:refs/remotes/${REMOTE}/${LIVE_DATA_BRANCH}"
  if ! git -C "${LIVE_DIR}" rebase "${REMOTE}/${LIVE_DATA_BRANCH}"; then
    git -C "${LIVE_DIR}" rebase --abort || true
    echo "Could not rebase live data changes cleanly." >&2
    exit 1
  fi
done

echo "Failed to publish live data artifacts after retries." >&2
exit 1
