#!/usr/bin/env python3
"""Refresh CRAN package metadata used by the website and CV."""

from __future__ import annotations

import argparse
from datetime import datetime
from email.parser import Parser
from pathlib import Path
import re
import sys
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "exdqlm"
DESCRIPTION_URL = f"https://cran.r-project.org/web/packages/{PACKAGE}/DESCRIPTION"
PACKAGE_URL = f"https://CRAN.R-project.org/package={PACKAGE}"
DOI_URL = f"https://doi.org/10.32614/CRAN.package.{PACKAGE}"
DATA_PATH = ROOT / "_data" / "cran_packages.yml"
CV_PATH = ROOT / "cv" / "antonio_aguirre_cv.tex"


def fetch_text(url: str) -> str:
    request = Request(
        url,
        headers={"User-Agent": "antonio-de-leon.com CRAN metadata updater"},
    )
    with urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8", errors="replace")


def published_label(published: str) -> str:
    try:
        parsed = datetime.strptime(published, "%Y-%m-%d")
    except ValueError:
        return published
    return f"{parsed.strftime('%B')} {parsed.day}, {parsed.year}"


def parse_cran_description(text: str) -> dict[str, str]:
    description = Parser().parsestr(text)
    version = (description.get("Version") or "").strip()
    date_publication = (description.get("Date/Publication") or "").strip()
    published = date_publication.split()[0] if date_publication else ""

    if not re.fullmatch(r"\d+(?:\.\d+)*", version):
        raise RuntimeError(f"Could not parse CRAN version for {PACKAGE!r}.")
    if published and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", published):
        raise RuntimeError(f"Could not parse CRAN publication date: {published!r}.")

    return {
        "package": PACKAGE,
        "version": version,
        "published": published,
        "published_label": published_label(published) if published else "",
        "source": "CRAN",
        "package_url": PACKAGE_URL,
        "description_url": DESCRIPTION_URL,
        "doi_url": DOI_URL,
    }


def render_yaml(metadata: dict[str, str]) -> str:
    return (
        "# Generated by scripts/update_cran_package_metadata.py. Do not edit by hand.\n"
        f"{PACKAGE}:\n"
        f"  package: \"{metadata['package']}\"\n"
        f"  version: \"{metadata['version']}\"\n"
        f"  published: \"{metadata['published']}\"\n"
        f"  published_label: \"{metadata['published_label']}\"\n"
        f"  source: \"{metadata['source']}\"\n"
        f"  package_url: \"{metadata['package_url']}\"\n"
        f"  description_url: \"{metadata['description_url']}\"\n"
        f"  doi_url: \"{metadata['doi_url']}\"\n"
    )


def update_cv_text(text: str, version: str) -> str:
    text, software_count = re.subn(
        r"CRAN v\d+(?:\.\d+)*; JSS software article submitted",
        f"CRAN v{version}; JSS software article submitted",
        text,
    )
    text, publication_count = re.subn(
        r"companion R package released on CRAN, version \d+(?:\.\d+)*\.",
        f"companion R package released on CRAN, version {version}.",
        text,
    )

    if software_count != 1:
        raise RuntimeError(f"Expected one CV research-software version line; found {software_count}.")
    if publication_count != 1:
        raise RuntimeError(f"Expected one CV publication version line; found {publication_count}.")

    return text


def write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    old_content = path.read_text(encoding="utf-8") if path.exists() else ""
    if old_content == content:
        return False

    if check:
        print(f"{path.relative_to(ROOT)} is stale.", file=sys.stderr)
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Updated {path.relative_to(ROOT)}.")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero if generated metadata or CV text would change.",
    )
    args = parser.parse_args()

    metadata = parse_cran_description(fetch_text(DESCRIPTION_URL))
    changed = False

    changed |= write_if_changed(DATA_PATH, render_yaml(metadata), check=args.check)

    cv_text = CV_PATH.read_text(encoding="utf-8")
    changed |= write_if_changed(
        CV_PATH,
        update_cv_text(cv_text, metadata["version"]),
        check=args.check,
    )

    if args.check and changed:
        return 1

    if not changed:
        print(f"{PACKAGE} metadata already current at {metadata['version']}.")
    else:
        print(f"{PACKAGE} metadata refreshed at {metadata['version']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
