name: Verify site build

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler: 2.5.23
          bundler-cache: true

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace
